import { WidgetDefinition } from './types'

export const GRID_COLUMNS = 20
export const CURRENT_DASHBOARD_VERSION = 2

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    id: 'tasks',
    title: 'Tasks & Timeline',
    description: 'Scheduled activities, habits, quick tasks, and agenda items',
    category: 'Habits',
    defaultEnabled: true,
    defaultW: 13,
    defaultH: 8,
    minW: 8,
    maxW: 20,
    minH: 4,
    maxH: 30,
  },
  {
    id: 'workHours',
    title: 'Work Hours',
    description: 'Track work presence, active timer, and weekly goal progress',
    category: 'Work',
    defaultEnabled: true,
    defaultW: 7,
    defaultH: 5,
    minW: 6,
    maxW: 12,
    minH: 3,
    maxH: 10,
  },
  {
    id: 'journal',
    title: 'Journal Today',
    description: 'Daily reflections, mood, and quick notes',
    category: 'Habits',
    defaultEnabled: true,
    defaultW: 7,
    defaultH: 3,
    minW: 5,
    maxW: 12,
    minH: 2,
    maxH: 8,
  },
  {
    id: 'leaveBalance',
    title: 'Leave Balance',
    description: 'Vacation, sick, and personal time-off statistics',
    category: 'Work',
    defaultEnabled: true,
    defaultW: 7,
    defaultH: 4,
    minW: 5,
    maxW: 12,
    minH: 2,
    maxH: 8,
  },
  {
    id: 'weight',
    title: 'Weight Tracker',
    description: 'Log and monitor body weight trend sparkline',
    category: 'Health',
    defaultEnabled: true,
    defaultW: 7,
    defaultH: 4,
    minW: 5,
    maxW: 12,
    minH: 3,
    maxH: 8,
  },
  {
    id: 'recentDocuments',
    title: 'Recent Vault Documents',
    description: 'Quick access to recently opened secure files',
    category: 'Vault',
    defaultEnabled: true,
    defaultW: 7,
    defaultH: 4,
    minW: 5,
    maxW: 12,
    minH: 3,
    maxH: 8,
  },
  {
    id: 'leetcodePOTD',
    title: 'LeetCode POTD',
    description: "Today's daily LeetCode coding problem",
    category: 'Coding',
    defaultEnabled: false,
    defaultW: 7,
    defaultH: 3,
    minW: 5,
    maxW: 12,
    minH: 3,
    maxH: 8,
  },
  {
    id: 'gfgPOTD',
    title: 'GFG POTD',
    description: "Today's GeeksforGeeks problem of the day",
    category: 'Coding',
    defaultEnabled: false,
    defaultW: 7,
    defaultH: 3,
    minW: 5,
    maxW: 12,
    minH: 3,
    maxH: 8,
  },
]

export function getWidgetDefinition(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find(w => w.id === id)
}
